### ISSUE TITLE
Add a button to make an export from any institution or Collection search result 

### ISSUE THREAD

**Issue by ManonGros** [gbif/hp-grscicoll#1]
**Is your feature request related to a problem? Please describe.**
This is a request I get every now and then from Node Mangers or people who want to get an overview of what is in their country. "Could I get a spreadsheet of all the Collections in the US?"

**Describe the solution you'd like**
When searching on the GRSciColl institution or collection interface, I want to be able to click a button that export my search result as a spreadsheet.

**Describe alternatives you've considered**
Right now this can be done via the API: https://www.gbif.org/developer/registry#collection but many people aren't familiar with APIs,

**Additional context**
See above

**Comment by MortenHofft** [comment]
https://grscicoll.hp.gbif-staging.org/reports/
I added this when we did the initial site. The idea being that it would serve exactly that audience.
That isn't to say that we couldn't/shouldn't add a filtered option as well, but I imagine that the list of reports was more accessable for that audience

**Comment by ManonGros** [comment]
I remember now yes. And although those reports would likely cover most cases, we have had more custom cases like "Federal US collections" or "Herbarium". I think with the integration of collection descriptors, we might start to have people asking for things like "export of entomology collections" (which I was asked once but couldn't really do anything about).

This wouldn't have to be implemented before the portal goes live though. The country reports would be enough for most cases.
