### ISSUE TITLE
Spanish translation of search widget shows unexpected text

### ISSUE THREAD

**Issue by ManonGros** [gbif/hp-grscicoll#108]
**Describe the bug**
This happens both in the collection and in the institution searches. Some text appears where it shouldn't. See the screenshot below.

**To Reproduce**
1. Go to https://grscicoll.hp.gbif-staging.org/es/institution/search
2. Click on `mà`

**Expected behavior**
The text should only correspond to the names of the filters.

**Screenshots**

<img width="1286" alt="Screenshot 2024-02-28 at 15 15 00" src="https://github.com/gbif/hp-grscicoll/assets/7677271/8dd09002-c215-403a-afcb-247866a988ff">

**Comment by MortenHofft** [comment]
It is the translation that is wrong as far as I can see. And it probably is so as a result of the way Crowdin helps by autofilling translations that looks similar.

**Comment by ManonGros** [comment]
I have tried to improve the translations, I think this is mostly ok now
