### ISSUE TITLE
Add the possibility to filter for specimens available in GBIF

### ISSUE THREAD

**Issue by ManonGros** [gbif/hp-grscicoll#12]
The API allows to do that now: https://github.com/gbif/registry/issues/502 It would be great to have it in the web UI as well.

**Comment by MortenHofft** [comment]
https://github.com/gbif/gbif-web/commit/c4801baa80a5b97b971ddcd7cb9d96cef2a62fd4
https://github.com/gbif/gbif-web/commit/fed46e3511baf4b2371cbfffed16895616eb7f98
