### ISSUE TITLE
Translation in Traditional Chinese

### ISSUE THREAD

**Issue by ckotwn** [gbif/hp-grscicoll#149]
It seems like the /zh folder hosts the translation in Simplified Chinese. I am looking to offer one in Traditional Chinese. Would it be possible to create /zh-tw (as GBIF.org) for Traditional Chinese, please?

**Comment by ManonGros** [comment]
@ckotwn the translations are handled directly in Crowdin, you shouldn't modify the files in GitHub. We could potentially add Traditional Chinese in Crowdin. @kcopas what do you think?

**Comment by kcopas** [comment]
Added—strings are now available.

Have at it @ckotwn !
