### ISSUE TITLE
Possibly link to discourse for community discussion

### ISSUE THREAD

**Issue by ManonGros** [gbif/hp-grscicoll#15]
As we have a growing community. It would be nice to have dedicated space for GRSciColl. I think discourse could be that place. We  could consider having a GRSciColl tag in the discourse forum.

**Comment by vechocho** [comment]
I think that would help.

**Comment by ManonGros** [comment]
We now have a discourse category! https://discourse.gbif.org/t/about-the-global-registry-of-scientific-collections-category/

**Comment by ManonGros** [comment]
added on contact page: https://grscicoll.hp.gbif-staging.org/contact/
