### ISSUE TITLE
Missing collection while searching by Institution

### ISSUE THREAD

**Issue by EstebanMH-SiB** [gbif/hp-grscicoll#165]
In collections section, when we search for Institution [Universidad de Nariño](https://scientific-collections.gbif.org/collection/search?institution=7c7ad91d-8590-42d7-ab73-6770cf61c383) it only shows 2 collections:
![image](https://github.com/user-attachments/assets/488b24cf-2521-460f-9c3b-b05d02b4c4ec)

But this institution have 3 collections: 
![image](https://github.com/user-attachments/assets/34ebdbba-2cea-47b9-ba60-3d88b8febd08)

Additionally, if we search using the code of Colección Microbiológica de la Universidad de Nariño [CMUN](https://scientific-collections.gbif.org/collection/search?code=CMUN), the collection does not shows:
![image](https://github.com/user-attachments/assets/c775d88a-2fab-40d3-9847-fc700c640ebc)

The only difference I found with the other collections, is that CMUN has the option "Display on NHC portal" as no, but I am not aware if this also affects the GRSciColl visibility in any way.

**Comment by MortenHofft** [comment]
That is exactly what it does. The site is configured to only show records that has been flagged as relevant for a **N**atural **H**istory **C**ollection site https://github.com/gbif/hp-grscicoll/blob/master/_includes/js/config.js#L72

ping @ManonGros

**Comment by ManonGros** [comment]
Thanks Morten!
Yes @EstebanMH-SiB this field is for hiding/showing records on Natural History Portals (including GRSciColl). This is the definition we have for the field at the moment:
> Should this collection be displayed on Natural History Collection portals? By default yes (unless this collection doesn't have any specimen relating to Natural History).

Let me know if you think this could be improved, thanks!

**Comment by EstebanMH-SiB** [comment]
Thank you for the clarification, we were not aware that NHC option included GRSciColl. Maybe we can edit the definition to explicit state that NHC includes GRSciColl?, something like:

> Should this collection be displayed on Natural History Collection portals **(including GRSciColl)**? By default yes (unless this collection doesn't have any specimen relating to Natural History). **If you choose no, this collection will not be searchable in those portals**

**Comment by ManonGros** [comment]
Thanks Esteban, I have updated the definition accordingly for the English version
