### ISSUE TITLE
Collections cannot be searched by institution key

### ISSUE THREAD

**Issue by ManonGros** [gbif/hp-grscicoll#169]
**Describe the bug**
This doesn't seem to work: https://scientific-collections.gbif.org/collection/search?institution=dcb3162a-9409-4785-a86a-fa6b9b805d1d
But the API calls does: https://api.gbif.org/v1/grscicoll/collection/search?institution=dcb3162a-9409-4785-a86a-fa6b9b805d1d

I am not sure why. @MortenHofft could you take a look? Thanks!

**Comment by MortenHofft** [comment]
Both work now, but we have seen something like it before. 
It is a case of the API failing. I cannot do anything about that. But the issue arise because the error is cached somewhere. That we should be able to fix.

**Comment by ManonGros** [comment]
@MortenHofft https://scientific-collections.gbif.org/collection/search?institution=dcb3162a-9409-4785-a86a-fa6b9b805d1d still doesn't give me the result I expect. This is a bit surprising.
