### ISSUE TITLE
"Add new collection" button/link on institution pages?

### ISSUE THREAD

**Issue by ManonGros** [gbif/hp-grscicoll#20]
I am not entirely sure about this so it would be great to have your input @MortenHofft @javiesgm

I think it could be helpful if there was a "suggest new collection" button visible from institution pages, maybe on the collection tab: https://grscicoll.hp.gbif-staging.org/institution/7a5c72e9-686a-46a0-aa87-8cfba951e6b8/collections.

Right now, the only place we have put these links are from our how to page: https://grscicoll.hp.gbif-staging.org/how-to/#how-to-add-a-collection-or-an-institution-to-grscicoll.
Perhaps it would be nice to also have it on institution page (we have a lot of institution entries but not so many collection entries.)

What do you think?

**Comment by MortenHofft** [comment]
I think the `Edit` is prominent enough that it isn't critical. But it makes sense to me to add it again under the institution/key/collections tab. It could just be a small comment in the bottom of the list.
