### ISSUE TITLE
Make institution map clickable

### ISSUE THREAD

**Issue by ManonGros** [gbif/hp-grscicoll#22]
**Is your feature request related to a problem? Please describe.**
I would like to be able to click on a dot on the institution map and have a link to the institution entry

**Describe the solution you'd like**
I know this is possible because I have seen it here: https://us-collections.hp.gbif-staging.org/institution/search
I just don't know how to enable it.

**Comment by MortenHofft** [comment]
Good question. That sounds like a bug
