### ISSUE TITLE
Show more fields on Institution and collection pages

### ISSUE THREAD

**Issue by ManonGros** [gbif/hp-grscicoll#23]
Some fields are empty for most entries but for those entries that have information, the fields should be displayed.
For example, see for example this entry: https://registry.gbif.org/collection/187a8a55-7de6-4230-8250-7d4ee274004f
that comes up in this search (https://grscicoll.hp.gbif-staging.org/collection/search?contentType=BIOLOGICAL_FECES).

We could have a `see more` button or such to display more than the the current set of fields.

**Comment by MortenHofft** [comment]
I've added contentType and preservationType
What about notes. Is that generally of a quality/content that makes sense to show?
