### ISSUE TITLE
Link color contrast

### ISSUE THREAD

**Issue by MortenHofft** [gbif/hp-grscicoll#26]
The link contrast is very low. The links almost appears as white holes in the text I find. 
The contrast ratio is 2.7 which is fairly low. Should we consider increasing that by choosing a darker tone for the links?

example page https://grscicoll.hp.gbif-staging.org/about/

**Comment by ManonGros** [comment]
I can pick a darker color. Maybe @javiesgm has suggestions?

**Comment by javiesgm** [comment]
How about #538e91 ?

**Comment by ManonGros** [comment]
Let's try it! Where can I change the hyperlink colour?

**Comment by ManonGros** [comment]
Thanks Morten!

I changed the color. The text is more visible but links don't exactly pop out in the text. What do you think?

**Comment by ManonGros** [comment]
@javiesgm I tried the colour you suggested but, I think the links disappear in the text.
So I tried the same color that is used to highlight the items in the menu on the right.

Here are different results for my testing, I like #05a8fa the best. What do you think?

## #538e91
<img width="1046" alt="Screenshot 2023-09-27 at 12 08 24" src="https://github.com/gbif/hp-grscicoll/assets/7677271/a977ade4-2708-4220-a957-3d5232491609">

## #40c0ff
<img width="1131" alt="Screenshot 2023-09-27 at 12 17 47" src="https://github.com/gbif/hp-grscicoll/assets/7677271/3eb2aa85-9cc9-4412-b2cd-f9292939e403">


## #05a8fa
<img width="1093" alt="Screenshot 2023-09-27 at 12 26 13" src="https://github.com/gbif/hp-grscicoll/assets/7677271/375c7ce5-3588-440d-b54d-c64c88d434f7">

**Comment by javiesgm** [comment]
I agree. Let's keep #05a8fa, it looks a little odd in relation to the button's color, but it makes sense regarding contrast and visibility.

**Comment by javiesgm** [comment]
How about an orange like this one? #F08177 
![Screenshot 2023-09-27 at 13 44 08](https://github.com/gbif/hp-grscicoll/assets/14220404/c9d16a3b-30b5-436a-bb55-b464b7876410)
![Screenshot 2023-09-27 at 13 43 08](https://github.com/gbif/hp-grscicoll/assets/14220404/d8ffe123-2eb2-40f1-9ed1-81db2bf6d326)

**Comment by javiesgm** [comment]
@MortenHofft I edited the [main.css](https://github.com/gbif/hp-grscicoll/blob/master/_sass/_main.scss) to change the border color on the table of contents. I hope it's alright. If not, could you let me know how to do it properly?
