### ISSUE TITLE
Set up final URL for the website

### ISSUE THREAD

**Issue by ManonGros** [gbif/hp-grscicoll#29]
I think we should use
scientific-collections.gbif.org

with the following URLs redirecting it to it:
grscicoll.gbif.org
https://www.gbif.org/grscicoll
grscicoll.org

Am I missing anything?

**Comment by MattBlissett** [comment]
I've set up https://scientific-collections.gbif.org/, the site will deploy there if you make a GitHub release.

http://grscicoll.org already redirects to https://www.gbif.org/grscicoll, and the latter can be redirected by Morten once the new site is deployed.

I don't see any need for grscicoll.gbif.org, it's never been used and just makes yet another possible identifier.

**Comment by timrobertson100** [comment]
Thanks @MattBlissett @ManonGros 

When things settle I think we should consider giving better and non-ambiguous advice as what people should put as ID in DwC records, which currently recommends:

```
http://grscicoll.org/institution/museum-southwestern-biology
https://www.gbif.org/grscicoll/institution/e3d4dcc4-81e2-444c-8a5c-41d1044b5381
```

We don't want to be managing redirect hell and should be thinking about maintaining stability for at least 10 years. 
On the pages, I think it would be good to have a really clear "to link to this entry in data, we recommend using <this identifier>".

**Comment by MattBlissett** [comment]
Some institutions also have LSIDs, and they are set up to redirect to the current site: [urn:lsid:biocol.org:col:15867](https://lsid.info/urn:lsid:biocol.org:col:15867) (although arguably they should go to a machine-readable representation when not accessed using a web browser).

**Comment by timrobertson100** [comment]
Not for decision here, but I do wonder if LSID may be a sensible option for GBIF to consider... e.g. `urn:lsid:gbif.org:collection:<uuid>` and similar for Taxa, our Specimen record view etc.

**Comment by ManonGros** [comment]
@timrobertson100 

The official FAQ on GBIF is the following:
https://www.gbif.org/faq?question=how-can-i-improve-the-matching-of-occurrence-records-with-grscicoll

I have put
> https://www.gbif.org/grscicoll/institution/e3d4dcc4-81e2-444c-8a5c-41d1044b5381

because some times entries don't have other identifiers. I am happy to just use the same text as the GBIF FAQ. Should I just do that?

PS: you are very welcome to make the edits directly https://github.com/gbif/hp-grscicoll/blob/master/faq.md#how-to-link-specimen-related-occurrences-published-on-gbif-to-grscicoll-entries
