### ISSUE TITLE
Institution (and collection) numbers should be consistent

### ISSUE THREAD

**Issue by ManonGros** [gbif/hp-grscicoll#42]
On the website's main page, we show 8,347 institutions, but on the search interface and TSV export, the number shown is `7,537 results`.
After checking with Marcos, it seems this number corresponds to the Active entries only.
I think all the entries should be included in the searches and exports. At least until we decide what to do with the `active` field. Many editors forget to tick the `active` checkbox and I wouldn't want their entries to be excluded from the export.

@MortenHofft, is this something we can change?

**Comment by MortenHofft** [comment]
Which number do you prefer?

The site only shows active institutions as it is now. So the number on the homepage is wrong. That can be changed in the yml files by adding the appropriate filter
https://github.com/gbif/hp-grscicoll/blob/master/_data/navCards.yml#L85

Alternatively we do not filter institutions to only show active ones, but show all. then the number on the homepage is correct.
That is done in the widget config https://github.com/gbif/hp-grscicoll/blob/master/_includes/js/config.js#L72C19-L72C19

**Comment by ManonGros** [comment]
Thanks Morten!
