### ISSUE TITLE
Renaming files cause issues with crowdin

### ISSUE THREAD

**Issue by MortenHofft** [gbif/hp-grscicoll#66]
@kcopas and @ManonGros 

Apparently renaming the file `road-map` to `roadmap` cause issues with Crowdin. It isn't to say that we should never do it. But the permalink attribute decides what the public url is, so in most cases we can probably just use that for renaming. I will look at the merge conflict.

https://github.com/gbif/hp-grscicoll/pull/65

**Comment by ManonGros** [comment]
Thanks @MortenHofft I don't think we need to rename files, next time, we can change the permlink and tag.
