### ISSUE TITLE
Lack of a favicon

### ISSUE THREAD

**Issue by qgroom** [gbif/hp-grscicoll#67]
**Is your feature request related to a problem? Please describe.**

The GRSciColl website lacks a favicon. This makes it hard to find in a series of tabs on your browser. It seems trivial, but you tend to miss it when it is not there.

**Describe the solution you'd like**
Just to add a favicon

**Describe alternatives you've considered**
There are no alternatives

**Additional context**
GRSciCol is one of these tabs
<img width="278" alt="Screenshot 2023-11-02 095450" src="https://github.com/gbif/hp-grscicoll/assets/5530576/77f6416f-87ca-414d-84ef-8a37e427cf2c">

**Comment by MortenHofft** [comment]
ping @ManonGros and @javiesgm I suppose we need to design one unless we reuse the one from gbif.org
Document on how to add it https://hp-theme.gbif-staging.org/favicon

**Comment by javiesgm** [comment]
Thanks, @MortenHofft! I think we should reuse GBIF's favicon until we further develop GRSciColl's visual identity. I'll update it using the documentation.

**Comment by javiesgm** [comment]
Done! I think

**Comment by qgroom** [comment]
Thanks! The GBIF icon is just fine
