### ISSUE TITLE
Country-specific search bar

### ISSUE THREAD

**Issue by ManonGros** [gbif/hp-grscicoll#72]
**Is your feature request related to a problem? Please describe.**
This is a suggestion made by one of our Regional contractors (@rabetrano) in order to improve GRSciColl relevance for users.

**Describe the solution you'd like**
> it would be useful also to add a country-specific search bar to the website. This would work like the one on the GBif portal, automatically finding the user's location and showing information tailored to their country. It'll make the user experience better and help people find country-specific collections easily.

![Capture d'écran 2023-11-06 061203](https://github.com/gbif/hp-grscicoll/assets/7677271/a6d632ae-229c-4dc0-8ce4-86d34708d6e9)

We could have a link to institution searches with a preselected country. For example "Institutions in Madagascar". Not sure where this would be best put, under the search bar like on GBIF.org? Right now we have the link to the video.
What do you think @javiesgm ?

**Comment by javiesgm** [comment]
That's a good idea. Perhaps something like this? 
![home-links-v1](https://github.com/gbif/hp-grscicoll/assets/14220404/a481a898-0ed2-46be-a796-9e9c2b8921ec)

**Comment by javiesgm** [comment]
However, this needs @MortenHofft touch. The triangle is a glyph (▶). I could upload the location icon to the assets folder unless it's easier to get from Google fonts (https://fonts.google.com/icons?selected=Material+Symbols+Outlined:my_location:FILL@0;wght@400;GRAD@0;opsz@48&icon.query=location)

**Comment by ManonGros** [comment]
Thanks @javiesgm it looks good to me!
@MortenHofft I don't know how this can be set up, how do we know which country the user is from?

**Comment by MortenHofft** [comment]
We don't. But we can try to guess based on the ip address.

**Comment by MortenHofft** [comment]
The most problematic is really the country name for me. I do not really have access to that in all translations. How would "Institutions nearby" work and then link to the country?

**Comment by ManonGros** [comment]
Thanks for your input Morten! It is also ok to close or leave the issue if it would be too time consuming to do.

I suppose this part could remain in English. "Institutions nearby" would also be ok.

Once again, we could also put a label on this suggestion like "not possible at the moment" and reevaluate later.

**Comment by MortenHofft** [comment]
I've added a proxy endpoint in the graphql project to get location. translations are taking from another project and stitched together. And translations is crudely templated using jekylls Liquid and javascript. It isn't pretty but it works.

**Comment by MortenHofft** [comment]
@javiesgm I didn't use the exact icons you mention. We use font awesome everywhere else on the site so I took one of theirs instead.
