### ISSUE TITLE
Add Plausible for analytics

### ISSUE THREAD

**Issue by ManonGros** [gbif/hp-grscicoll#80]
**Is your feature request related to a problem? Please describe.**
It would be nice to have analytics on the website like for gbif https://plausible.io/gbif.org.

**Describe the solution you'd like**
I can see others have added plausible for their hosted portals: https://github.com/gbif/hp-living-norway/commit/faca364600e2a42e867a39c5a6c2a41f03d1a665. Could I do the same? Do I need to use some share Plausible credentials? (It doesn't look like it from the commit but perhaps I am missing something?)

**Comment by MortenHofft** [comment]
does this help? https://hp-theme.gbif-staging.org/measurements

**Comment by ManonGros** [comment]
Yes! Thanks Morten! I haven't bookmarked the documentation but no more! Thanks again.

**Comment by MattBlissett** [comment]
This is ready for the snippet to be added: https://plausible.io/scientific-collections.gbif.org

**Comment by ManonGros** [comment]
Thanks @MattBlissett !
Hopefully, I did it correctly.
