### ISSUE TITLE
Missing names on dashboard

### ISSUE THREAD

**Issue by vechocho** [gbif/hp-grscicoll#97]
**Describe the bug**
Some names are not showing on some views on the dashboard, this happens in Ecuador HP as well.

If you go to the dashboard on a collection page on the section RecordedBy you'll see blank colectors:

![image](https://github.com/gbif/hp-grscicoll/assets/13081080/cd892ddb-10ae-479f-909a-d060fd1c49a3)

If you change the type of view on the window, you'll see those names:

![image](https://github.com/gbif/hp-grscicoll/assets/13081080/55efa6e0-f35d-4a1f-b02f-a276abf19db4)

collection: 98446879-1ad8-42e6-8d91-c694deec57ac

**Comment by MortenHofft** [comment]
I found the problem. It is an inconsistency in how we show the names. For the table we try to show the name with proper casing etc. We do so by first getting distinct values from the index. But the index only deals with lower case values without diacritics/accents. So to get those we do a lookup for matches, and then select the first occurrence. Then we parse the original string to get a recorder name that match the one in the index. And I had missed that I should remove diacritics when performing that match, and so there was no match and hence a blank value.
